version: '3'

services: 
  frontend:
    image: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    volumes:
      - /app/node_modules
      - ./:/app
    container_name: "frontend"
  
  backend:
    image: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8443"
    volumes:
      - /home/ubuntu/docker-volume/ssl:/root
    container_name: "backend"
